### ISSUE TITLE
Highlighting on input fields in the 'contact.html' page not working.

### ISSUE THREAD

**Issue by dulgherucosmin** [dulgherucosmin/Hero-Repo#1]
In the form element in 'contact.html', I have added the CSS for it to style the inputs accordingly, however when the input is selected, the CSS for it does not work.

My (not working) code:

```css
/* This part works */
main .comment-form input {
    margin: .25rem 0;

    border: 2px solid var(--main);
    border-radius: 32px;
    background-color: var(--secondarywhite);
}

/* This part does not work*/
main .comment-form input:focus {
    border: 2px solid var(--accent);
}
```

Note: whenever I try to change something else, for example `background-color: red;` it **does** work. I may just be stupid.
